// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateNoteInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Mutation struct {
}

type Note struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Query struct {
}
