version: "3.7"

networks:
  monitoring:
    driver: bridge

services:
  db:
    container_name: wd_database
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_USER: WebDad
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: webdad
    ports:
      - 5432:5432
    networks:
      - monitoring

  adminer:
    container_name: wd_adminer
    image: dockette/adminer:full
    restart: always
    ports:
      - 5051:80
    networks:
      - monitoring

  rabbitmq:
    container_name: wd_rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672   
      - 15672:15672 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - monitoring

volumes:
  rabbitmq_data:
    driver: local