version: "3.7"

networks:
  monitoring:
    driver: bridge

services:
  db:
    container_name: wd_database
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_USER: WebDad
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: webdad
    ports:
      - 5432:5432

  adminer:
    container_name: wd_adminer
    image: dockette/adminer:full
    restart: always
    ports:
      - 5051:80