version: "3.7"

networks:
  monitoring:
    driver: bridge

services:
  db:
    container_name: wd_database
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_USER: WebDad
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: webdad
    ports:
      - 5432:5432
    networks:
      - monitoring

  adminer:
    container_name: wd_adminer
    image: dockette/adminer:full
    restart: always
    ports:
      - 5051:80
    networks:
      - monitoring

  rabbitmq:
    container_name: wd_rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672   
      - 15672:15672 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - monitoring

  n8n:
    container_name: wd_n8n
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_USER_MANAGEMENT_DISABLED=true
      - WEBHOOK_URL=http://host.docker.internal:8080
      - DISCORD_WEBHOOK_URL=your_discord_webhook_url
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - monitoring

volumes:
  rabbitmq_data:
    driver: local
  n8n_data:
    driver: local